import os


class CONFIG:
    OANDA_API_KEY = os.getenv("OANDA_API_KEY")
    OANDA_ACCOUNT_ID = os.getenv("OANDA_ACCOUNT_ID")
    TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
    TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

    INSTRUMENT = "EUR_USD"
    CANDLE_GRANULARITY = "M5"
    CANDLE_COUNT = 50

    DEFAULT_UNITS = 1000
    COOLDOWN_SECONDS = 6

    RSI_OVERSOLD = 30
    RSI_OVERBOUGHT = 70

    LOGGING_LEVEL = "INFO"
 